// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_euL5BS1raBjZPPavkH7u8H6LyFoafN4',
    appId: '1:389508884327:web:315dfa90ef73ff21a6f1c2',
    messagingSenderId: '389508884327',
    projectId: 'lingobreeza',
    authDomain: 'lingobreeza.firebaseapp.com',
    storageBucket: 'lingobreeza.firebasestorage.app',
    measurementId: 'G-NPFMNHV27C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxsI27d-NcvvzKo3_wh0_6HUQvBoHIUdU',
    appId: '1:389508884327:android:ed384083ce8e087fa6f1c2',
    messagingSenderId: '389508884327',
    projectId: 'lingobreeza',
    storageBucket: 'lingobreeza.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYTNz9Kmf54SHeuPUx71cUB4ztByWf3f4',
    appId: '1:389508884327:ios:210b99101640f23ba6f1c2',
    messagingSenderId: '389508884327',
    projectId: 'lingobreeza',
    storageBucket: 'lingobreeza.firebasestorage.app',
    iosBundleId: 'com.example.lingobrezza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYTNz9Kmf54SHeuPUx71cUB4ztByWf3f4',
    appId: '1:389508884327:ios:210b99101640f23ba6f1c2',
    messagingSenderId: '389508884327',
    projectId: 'lingobreeza',
    storageBucket: 'lingobreeza.firebasestorage.app',
    iosBundleId: 'com.example.lingobrezza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_euL5BS1raBjZPPavkH7u8H6LyFoafN4',
    appId: '1:389508884327:web:e444388d0cc195baa6f1c2',
    messagingSenderId: '389508884327',
    projectId: 'lingobreeza',
    authDomain: 'lingobreeza.firebaseapp.com',
    storageBucket: 'lingobreeza.firebasestorage.app',
    measurementId: 'G-MJ4Q6M9DJQ',
  );
}
